CREATE TABLE USUARIO (
    NOME VARCHAR(255),
    SENHA VARCHAR(255),
    EMAIL VARCHAR(255) PRIMARY KEY
);

CREATE TABLE POSTAGEM (
    ID_POSTAGEM INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL_CREATOR VARCHAR(255),
    NOME VARCHAR(255),
    DESCRICAO VARCHAR,
    CIDADE VARCHAR(255),
    ESTADO VARCHAR(255),
    LONGADOURO VARCHAR(255),
    PATH_IMAGEM VARCHAR(255),
    FOREIGN KEY (EMAIL_CREATOR) REFERENCES USUARIO(EMAIL)
);


CREATE TABLE LISTA_DESEJO(
    ID_POSTAGEM INT ,
    EMAIL_CREATOR VARCHAR(255),
    FOREIGN KEY (ID_POSTAGEM) REFERENCES POSTAGEM(ID_POSTAGEM) ON DELETE CASCADE,
    FOREIGN KEY (EMAIL_CREATOR) REFERENCES USUARIO(EMAIL),
    PRIMARY KEY (ID_POSTAGEM, EMAIL_CREATOR)
);
